language: r
cache: packages
r_check_args: --as-cran 
r_build_args: --compact-vignettes=both
use_bioc: true
bioc_required: true

r:
  - release
  - devel

os:
  - linux
  - osx

matrix:
  fast_finish: true
  allow_failures:
  - r: devel

after_success:
  - Rscript -e 'covr::codecov()'

bioc_packages:
  - Biostrings

before_install:
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include"; fi

services:
  - xvfb

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
    - Rscript -e 'covr::codecov()'
