test_that("find_motifs detects correctly motif that is single unambiguous amino acid in sequences", {})
test_that("find_motifs detects correctly motif that is single unambiguous nucleotide in sequences", {})
test_that("find_motifs detects correctly motif that is single ambiguous amino acid in sequences", {})
test_that("find_motifs detects correctly motif that is single ambiguous nucleotide in sequences", {})
test_that("find_motifs detects correctly leading letters of amino acid sequences using '^'", {})
test_that("find_motifs detects correctly leading letters of nucleotide sequences using '^'", {})
test_that("find_motifs detects correctly letters at the end of amino acid sequences using '$'", {})
test_that("find_motifs detects correctly letters at the end of nucleotide sequences using '$'", {})
test_that("find_motifs detects correctly multiple-letter motifs in amino acid sequences", {})
test_that("find_motifs detects correctly multiple-letter motifs in nucleotide sequences", {})
test_that("find_motifs detects correctly multiple motifs in amino acid sequences", {})
test_that("find_motifs detects correctly multiple motifs in nucleotide sequences", {})