// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_tidysq_RCPPEXPORTS_H_GEN_
#define RCPP_tidysq_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace tidysq {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("tidysq", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("tidysq", "_tidysq_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in tidysq");
            }
        }
    }

    inline Rcpp::CharacterVector C_get_real_alph(Rcpp::CharacterVector sq) {
        typedef SEXP(*Ptr_C_get_real_alph)(SEXP);
        static Ptr_C_get_real_alph p_C_get_real_alph = NULL;
        if (p_C_get_real_alph == NULL) {
            validateSignature("Rcpp::CharacterVector(*C_get_real_alph)(Rcpp::CharacterVector)");
            p_C_get_real_alph = (Ptr_C_get_real_alph)R_GetCCallable("tidysq", "_tidysq_C_get_real_alph");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_get_real_alph(Shield<SEXP>(Rcpp::wrap(sq)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::CharacterVector >(rcpp_result_gen);
    }

    inline Rcpp::RawVector C_pack_raws(Rcpp::RawVector unpacked, const unsigned short alph_size) {
        typedef SEXP(*Ptr_C_pack_raws)(SEXP,SEXP);
        static Ptr_C_pack_raws p_C_pack_raws = NULL;
        if (p_C_pack_raws == NULL) {
            validateSignature("Rcpp::RawVector(*C_pack_raws)(Rcpp::RawVector,const unsigned short)");
            p_C_pack_raws = (Ptr_C_pack_raws)R_GetCCallable("tidysq", "_tidysq_C_pack_raws");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_pack_raws(Shield<SEXP>(Rcpp::wrap(unpacked)), Shield<SEXP>(Rcpp::wrap(alph_size)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::RawVector >(rcpp_result_gen);
    }

    inline Rcpp::RawVector C_pack_ints(Rcpp::IntegerVector unpacked, const unsigned short alph_size) {
        typedef SEXP(*Ptr_C_pack_ints)(SEXP,SEXP);
        static Ptr_C_pack_ints p_C_pack_ints = NULL;
        if (p_C_pack_ints == NULL) {
            validateSignature("Rcpp::RawVector(*C_pack_ints)(Rcpp::IntegerVector,const unsigned short)");
            p_C_pack_ints = (Ptr_C_pack_ints)R_GetCCallable("tidysq", "_tidysq_C_pack_ints");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_pack_ints(Shield<SEXP>(Rcpp::wrap(unpacked)), Shield<SEXP>(Rcpp::wrap(alph_size)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::RawVector >(rcpp_result_gen);
    }

    inline Rcpp::RawVector C_pack_chars(Rcpp::CharacterVector unpacked, Rcpp::CharacterVector alph) {
        typedef SEXP(*Ptr_C_pack_chars)(SEXP,SEXP);
        static Ptr_C_pack_chars p_C_pack_chars = NULL;
        if (p_C_pack_chars == NULL) {
            validateSignature("Rcpp::RawVector(*C_pack_chars)(Rcpp::CharacterVector,Rcpp::CharacterVector)");
            p_C_pack_chars = (Ptr_C_pack_chars)R_GetCCallable("tidysq", "_tidysq_C_pack_chars");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_pack_chars(Shield<SEXP>(Rcpp::wrap(unpacked)), Shield<SEXP>(Rcpp::wrap(alph)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::RawVector >(rcpp_result_gen);
    }

    inline Rcpp::RawVector C_pack_string(Rcpp::RawVector unpacked, Rcpp::CharacterVector alph) {
        typedef SEXP(*Ptr_C_pack_string)(SEXP,SEXP);
        static Ptr_C_pack_string p_C_pack_string = NULL;
        if (p_C_pack_string == NULL) {
            validateSignature("Rcpp::RawVector(*C_pack_string)(Rcpp::RawVector,Rcpp::CharacterVector)");
            p_C_pack_string = (Ptr_C_pack_string)R_GetCCallable("tidysq", "_tidysq_C_pack_string");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_pack_string(Shield<SEXP>(Rcpp::wrap(unpacked)), Shield<SEXP>(Rcpp::wrap(alph)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<Rcpp::RawVector >(rcpp_result_gen);
    }

    inline unsigned short C_get_alph_size(Rcpp::CharacterVector alph) {
        typedef SEXP(*Ptr_C_get_alph_size)(SEXP);
        static Ptr_C_get_alph_size p_C_get_alph_size = NULL;
        if (p_C_get_alph_size == NULL) {
            validateSignature("unsigned short(*C_get_alph_size)(Rcpp::CharacterVector)");
            p_C_get_alph_size = (Ptr_C_get_alph_size)R_GetCCallable("tidysq", "_tidysq_C_get_alph_size");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_get_alph_size(Shield<SEXP>(Rcpp::wrap(alph)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<unsigned short >(rcpp_result_gen);
    }

    inline std::vector<unsigned char> unpack_raws_to_std_vector(Rcpp::RawVector v, unsigned short alphabet_size) {
        typedef SEXP(*Ptr_unpack_raws_to_std_vector)(SEXP,SEXP);
        static Ptr_unpack_raws_to_std_vector p_unpack_raws_to_std_vector = NULL;
        if (p_unpack_raws_to_std_vector == NULL) {
            validateSignature("std::vector<unsigned char>(*unpack_raws_to_std_vector)(Rcpp::RawVector,unsigned short)");
            p_unpack_raws_to_std_vector = (Ptr_unpack_raws_to_std_vector)R_GetCCallable("tidysq", "_tidysq_unpack_raws_to_std_vector");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_unpack_raws_to_std_vector(Shield<SEXP>(Rcpp::wrap(v)), Shield<SEXP>(Rcpp::wrap(alphabet_size)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<std::vector<unsigned char> >(rcpp_result_gen);
    }

    inline unsigned int C_get_out_len(Rcpp::RawVector packed, const unsigned short alph_size) {
        typedef SEXP(*Ptr_C_get_out_len)(SEXP,SEXP);
        static Ptr_C_get_out_len p_C_get_out_len = NULL;
        if (p_C_get_out_len == NULL) {
            validateSignature("unsigned int(*C_get_out_len)(Rcpp::RawVector,const unsigned short)");
            p_C_get_out_len = (Ptr_C_get_out_len)R_GetCCallable("tidysq", "_tidysq_C_get_out_len");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_get_out_len(Shield<SEXP>(Rcpp::wrap(packed)), Shield<SEXP>(Rcpp::wrap(alph_size)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<unsigned int >(rcpp_result_gen);
    }

    inline unsigned short C_get_na_val(const unsigned short alph_size) {
        typedef SEXP(*Ptr_C_get_na_val)(SEXP);
        static Ptr_C_get_na_val p_C_get_na_val = NULL;
        if (p_C_get_na_val == NULL) {
            validateSignature("unsigned short(*C_get_na_val)(const unsigned short)");
            p_C_get_na_val = (Ptr_C_get_na_val)R_GetCCallable("tidysq", "_tidysq_C_get_na_val");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_C_get_na_val(Shield<SEXP>(Rcpp::wrap(alph_size)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<unsigned short >(rcpp_result_gen);
    }

}

#endif // RCPP_tidysq_RCPPEXPORTS_H_GEN_
