# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPP_pack_RAWS <- function(proto, alphabet, NA_letter) {
    .Call(`_tidysq_CPP_pack_RAWS`, proto, alphabet, NA_letter)
}

CPP_pack_INTS <- function(proto, alphabet, NA_letter) {
    .Call(`_tidysq_CPP_pack_INTS`, proto, alphabet, NA_letter)
}

CPP_pack_STRINGS <- function(proto, alphabet, NA_letter) {
    .Call(`_tidysq_CPP_pack_STRINGS`, proto, alphabet, NA_letter)
}

CPP_pack_STRING <- function(proto, alphabet, NA_letter) {
    .Call(`_tidysq_CPP_pack_STRING`, proto, alphabet, NA_letter)
}

CPP_unpack_RAWS <- function(sq, NA_letter) {
    .Call(`_tidysq_CPP_unpack_RAWS`, sq, NA_letter)
}

CPP_unpack_INTS <- function(sq, NA_letter) {
    .Call(`_tidysq_CPP_unpack_INTS`, sq, NA_letter)
}

CPP_unpack_STRINGS <- function(sq, NA_letter) {
    .Call(`_tidysq_CPP_unpack_STRINGS`, sq, NA_letter)
}

CPP_unpack_STRING <- function(sq, NA_letter) {
    .Call(`_tidysq_CPP_unpack_STRING`, sq, NA_letter)
}

C_get_real_alph <- function(sq) {
    .Call(`_tidysq_C_get_real_alph`, sq)
}

CPP_bite <- function(x, indices) {
    .Call(`_tidysq_CPP_bite`, x, indices)
}

CPP_find_invalid_letters <- function(x, dest_type) {
    .Call(`_tidysq_CPP_find_invalid_letters`, x, dest_type)
}

CPP_has <- function(x, motifs) {
    .Call(`_tidysq_CPP_has`, x, motifs)
}

Cpp_translate <- function(sq, table) {
    .Call(`_tidysq_Cpp_translate`, sq, table)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_tidysq_RcppExport_registerCCallable', PACKAGE = 'tidysq')
})
