# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPP_pack_RAWS <- function(proto, alphabet) {
    .Call(`_tidysq_CPP_pack_RAWS`, proto, alphabet)
}

C_get_real_alph <- function(sq) {
    .Call(`_tidysq_C_get_real_alph`, sq)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_tidysq_RcppExport_registerCCallable', PACKAGE = 'tidysq')
})
